baseURL = "https://anthhugo.github.io/blog/"
languageCode = "fr-fr"
title = "Hugo Casabella"
theme = "resume-hugo"
publishDir = "docs"

[params]
    firstName = "Hugo"
    lastName = "Casabella"
    address = "Lyon, France"
    contactNote = "Lead web developer" #used in QR code only
    profileImage = "img/me.jpeg"
    email = "hugo.casabella@gmail.com"
    description = "Software Engineer with experience leveraging agile, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = false
    showEducation = false
    showQr = true

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/hugo-casabella-15b01a163/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/anthHugo"

#[params.google.analytics]
#    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]